local Players = game:GetService("Players")

local Charm = require("../../../modules/Charm")
local fishingStore = require("../../shared/stores/fishingStore")
local types = require("../../shared/types")

export type FisherReeling = fishingStore.FisherReeling

local getAccount, setAccount = Charm.signal(types.accountTemplate)

local isFishing = Charm.computed(function()
	return fishingStore.isFishing(Players.LocalPlayer.Name)
end)

local isLuring = Charm.computed(function()
	return fishingStore.isLuring(Players.LocalPlayer.Name)
end)

local isReeling = Charm.computed(function()
	return fishingStore.isReeling(Players.LocalPlayer.Name)
end)

local function getFisher()
	return fishingStore.getFisher(Players.LocalPlayer.Name)
end

return {
	getAccount = getAccount,
	setAccount = setAccount,
	isFishing = isFishing,
	isLuring = isLuring,
	isReeling = isReeling,
	getFisher = getFisher,
}
